### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Gonzalox2** [AntonioDePau/MPStoPMF#1]
More than an issue, and sorry if this is restricted, how you know the lenght (in seconds) of the pmf? im trying a video, but it cuts at 1:15 seconds (the video lenght is 1:51 seconds) ...
Currently this is the program that leaves the video closest to its original, and it is not a problem with MPS since other programs leave it with a much shorter duration.
I hope can you helpme or answer my question

**Comment by AntonioDePau** [comment]
1. What program are you using to play the MPS video?
2. What program are you using to play the converted PMF?

The program merely adds a PMF header before the MPS bytes, so there should be no data loss and there's no reason for the video to become shorter. Any chance you could upload the MPS file to Mega (or some other file hosting website) and share it?

**Comment by Gonzalox2** [comment]
Thanks for the reply
The 'program' is a game, called PUMP IT UP ZERO (PSP) , i used UMD Stream Converter to make de MPS file
I already fix the problem, change the hexa value of the duration of the video (i dont know if the game use other formula), the 0x5c value , the formula i used its [90382 * seconds of the video] and transform into hexa (at least that its the most accuarate formula that the game use to read the duration of the video)
https://www.mediafire.com/file/y7vch2avf5mi2ni/00001.MPS/file
There is the MPS file that i used

**Comment by AntonioDePau** [comment]
> I already fix the problem

So this issue/question can be closed?

Just to confirm, you mean the bytes at offset 0x5c of the PMF are read by the game and used as the duration of the video?
