### ISSUE TITLE
Brightness Issue

### ISSUE THREAD

**Issue by insouso** [AntonioDePau/MPStoPMF#2]
Hi, sorry but whenever i convert the mps to pmf and put it in the game, the video plays REALLY dark, and the mps and pmf file plays just fine with the MCE-BE, with no brightness issue at all, do you know how i could fix this please? The game is Tenchu San Portable, im trying to make a english patch

Heres the mps and pmf playing just fine

https://github.com/AntonioDePau/MPStoPMF/assets/164597292/cf994045-2f9c-4ac8-9e68-1e16c6ec3b27

and heres a link to how the video plays in the game
https://youtu.be/WPGMlUiWXuI?si=Lk1VjdMQFOhwOvnI

**Comment by AntonioDePau** [comment]
Hey, have you tried repacking the game with the original video (if that's a thing that can be done), to discard the conversion being the issue? What change are you making to the video? VO change?

**Comment by insouso** [comment]
Im using umdgen to replace the files

**Comment by insouso** [comment]
the ps2 game cutscenes are in game, so i have no choice but to record then and replace the original ones

**Comment by insouso** [comment]
Never mind it i fixed it, thanks for the attetion tough
